name: pip-install

# Controls when the workflow will run
on:
  # Manual trigger from the Actions tab only
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install
      run: pip install PyStemmer
